### PR TITLE
Add ninja blaze

### PR DESCRIPTION
**Pull request by Grinion**

### CODE REVIEW

**Comment by jeongeunlee1209** [comment]
Thank you for submitting the PR on adding Ninja Blaze as one of the Mobile Dapp on the Cosmostation wallet.
Our development team tested the functionality and found out that the Cosmostation wallet is not able to be connected when the 'Connect Wallet' is clicked. (The option of Cosmostation wallet is disabled, thus not able to connect the wallet)

In order to be merged onto the following directory (wallet_mobile/dapp/dapps.json) and displays as one of the operating Dapps on Comsostation mobile, the wallet has to be connected and the users should be able to interact with the Cosmostation app. Please add the functionality on the Dapp so that we are able to review again and merge the PR. Regarding on how to integrate, please refer to the docs link below

https://docs.cosmostation.io/mobile

**Review by Hla24 — COMMENTED** [review]
[trust wallet ]()

**Review by Hla24 — COMMENTED** [review]
[trust wallet ]()

**Comment by Kwonhyukjoon** [comment]
https://github.com/cosmostation/chainlist/commit/cc09ebf7e2c8f2a5120effae2e42342981008da5

commit complete

**Pull request closed without merging**
