### PR TITLE
Updated all BackBone Labs assets across the cosmos

### PR DESCRIPTION
**Pull request by tvl83**
Added all information for:

- bLUNA
- bWHALE
- bHUAHUA
- bJUNO
- bKUJI
- bOSMO

### CODE REVIEW

**Comment by tvl83** [comment]
I see there's a conflict still. I don't know why it's showing that as a conflict.

**Comment by wannabit-yongjoo** [comment]
Let me merge this pr with another task. .
sorry for being annoying. 
I will ping here

Thanks a lot

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/chainlist/commit/cb4eca8089cdea19a2460b094df61c57d67a7c95

data merged
thanks a lot

**Comment by tvl83** [comment]
thank you

**Pull request closed without merging**
