### PR TITLE
Update IBC denom for medasdigital-2

### PR DESCRIPTION
**Pull request by oxygene76**

### CODE REVIEW

**Comment by oxygene76** [comment]
Update denom for medasdigital-2->osmosis-1

**Comment by stamper-dev** [comment]
Hello,

Upon reviewing the coin, we found that currently on https://app.osmosis.zone/, the MEDAS coin is registered under the MEDAS information from medasdigital-1. If the relayer and IBC denom are to change with the transition to medasdigital-2, how will the existing ibc/01E94A5FF29B8DDEFC86F412CC3927F7330E9B523CC63A6194B1108F5276025C be handled? Will the MEDAS coin from medasdigital-1, which has already been transferred to Osmosis, no longer be used?

Additionally, when checking the information for ibc/FBBC35295AA037DC0A77796B08DC3003EC918E18E75D61D675A0EEAC0643F36C registered under medasdigital-2, we observed that no IBC send has been executed successfully yet, and we cannot find information about this coin on https://app.osmosis.zone/ or https://docs.osmosis.zone/osmosis-core/asset-info/.

Could you please provide any additional identifiable information about this?

Thank you.

**Comment by oxygene76** [comment]
Good morning, medasdigital-2 is a hardfork from medasdigital-1 chain. So medasdigital-1 token Info could be fully removed and is replaced by medasdigital-2 Info. The pull request for assetlist ok osmosis has been done in parallel. The ibc send was yesterday eg with hash 9164AE1EBBA55A634D9A44C3C3A1CA620AE6D0999403F15FC0D43B877C9A7EDA

It seems the relayer info in mintscan is lagging but I do not know why?!

image

Best regards
Eike

**Comment by wannabit-yongjoo** [comment]
@stamper-dev please check.  relayer to display

**Pull request merged**
