### PR TITLE
Update param_2.json

### PR DESCRIPTION
**Pull request by Quasar-hub**
update grpc

### CODE REVIEW

**Comment by wannabit-yongjoo** [comment]
스크린샷 2024-11-05 오후 6 12 01
Hi @Quasar-hub 
gRpc endpoint not working.

**Comment by wannabit-yongjoo** [comment]
스크린샷 2024-11-05 오후 6 12 01
endpoint looks not working

**Comment by Quasar-hub** [comment]
updated

**Comment by wannabit-yongjoo** [comment]
@Quasar-hub

**Pull request merged**
