### PR TITLE
Add IBC representation of the NEOK token

### PR DESCRIPTION
**Pull request by vrde**
Follow up of this PR https://github.com/cosmostation/chainlist/pull/538.

### CODE REVIEW

**Comment by vrde** [comment]
@stamper-dev sorry for sounding pushy, is there anything you need from us to merge the PR? 🙇

**Comment by wannabit-yongjoo** [comment]
Dear @vrde 

For double check your PR
is your request asset [CW20](https://www.mintscan.io/evmos/evm/contract/0x655ecB57432CC1370f65e5dc2309588b71b473A9)?

If that please PR this [file](https://github.com/cosmostation/chainlist/blob/main/chain/evmos/contract.json) 
instead of this

**Comment by vrde** [comment]
> For double check your PR is your request asset [CW20](https://www.mintscan.io/evmos/evm/contract/0x655ecB57432CC1370f65e5dc2309588b71b473A9)?

Our token is both an ERC20 and an IBC coin. We made a proposal to the EVMOS chain for that, see https://app.evmos.org/governance?id=144

> If that please PR this [file](https://github.com/cosmostation/chainlist/blob/main/chain/evmos/contract.json) instead of this

In did that, see https://github.com/cosmostation/chainlist/pull/538, it's referenced in the description of this PR.

Our token is both an ERC20 and an IBC coin.

**Comment by vrde** [comment]
@stamper-dev :partying_face: :confetti_ball:

**Pull request merged**
