### PR TITLE
Add NINPO

### PR DESCRIPTION
**Pull request by iwillbuy**

### CODE REVIEW

**Comment by wannabit-yongjoo** [comment]
Hi @iwillbuy 
I can't not find your denom on-chain data.
I double checked with "factory/inj1sudjgsyhufqu95yp7rqad3g78ws8g6htf32h88/ninpo"  but no data.

please check more information for add asset

**Comment by iwillbuy** [comment]
Hi @wannabit-yongjoo 

Does this not support CW20 token on injective ?

**Comment by iwillbuy** [comment]
https://explorer.injective.network/contract/inj1sudjgsyhufqu95yp7rqad3g78ws8g6htf32h88/

**Comment by wannabit-yongjoo** [comment]
There are no dapp that use cw20 tokens yet, so currently we do not support them.

**Pull request closed without merging**
